name: 'Deploy on scratch org'
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - sprint-*
        paths:
            - 'force-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "$SALESFORCE_JWT_SECRET_KEY" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
      
    - name: Define CI org
      run: node_modules/sfdx-cli/bin/run force:org:create -v devhub -s -f config/project-scratch-def.json -a ciorg -d 1

    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push -u ciorg

    - name: Assign Permision Set
      run: node_modules/sfdx-cli/bin/run force:user:permset:assign --permsetname Recruitment_User

    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human -u ciorg

    - name: Clean env
      run: node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p
